source 'https://github.com/zhengya123/ZYModule.git'

platform :ios, '8.0'

target 'ZYCategoryKit_Example' do
  pod 'ZYCategoryKit', :path => '../'
  pod 'ZYImageModule'
  target 'ZYCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
